name: Build & Deploy Docs
on:
  push:
    branches:
      - master
      - actions

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/opensuse/tumbleweed:latest
      options: --privileged
    steps:
      - name: Update Distribution 🦎
        run: zypper dup -y
      - name: Install Prerequisites 🔧
        run: zypper in -y --no-recommends tar gzip git rsync
      - name: Checkout Repository 🛎️
        uses: actions/checkout@v2
      - name: Download C toolchain 🔮
        run: zypper in -y --no-recommends gcc
      - name: Download Rust toolchain 🦀
        run: zypper in -y --no-recommends rust cargo
      - name: Download Java toolchain ☕
        run: zypper in -y --no-recommends java java-devel
      - name: Build Documentation 📑
        run: cargo doc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: target/doc
